### ISSUE TITLE
Cache prevents updates to be visible

### ISSUE THREAD

**Issue by Globulle** [mhkeller/pulp2#7]
The comic I am interested in is updated monthly to include new pages. Last time it has been updated I was unable to see the changes when I opened it with my regular browser (Firefox) despite they appear on another one. I assume this comes from some cache data which remains stored somewhere.

Would it be possible to ask the client to delete cache at each new visit? Or each update? Or when the session is closed?

Thank you for your help.

**Comment by mhkeller** [comment]
Hmm cache busting is a tricky subject. I think handling this on a case-by-case would be better than putting it into the viewer. For instance, some people might want a client-side solution whereas others would prefer to set a cache header from the web server.

For your case, you could add a timestamp as a query parameter in the src line here https://github.com/mhkeller/pulp2/blob/master/public/index.html#L203-L205

So that when you do an update you add something like `?update-2` to the end of the image url. That *should* bust the cache.

Perhaps one thing that could be improved would be to no longer enforce an image naming convention. That way you could change the name of the images so something new, which would be more reliable.

**Comment by Globulle** [comment]
Ok, thank you for your advice.
