### ISSUE TITLE
Make icons still available in fullscreen mode

### ISSUE THREAD

**Issue by Globulle** [mhkeller/pulp2#9]
In fullscreen mode, the toolbar is absent. As it contains navigation tools (such as page number) it would be useful to be able to have it appear. For example this toolbar could be hidden and just appear (drop-down?) when the mouse is directed to the top of the screen.

I wish I could have implemented this myself but my knowledge in CSS is too weak. Thank you very much.

**Comment by mhkeller** [comment]
Ya that's a good idea. I'll work on an implementation.

**Comment by Globulle** [comment]
I will publish the last chapter of the comic I work on within a few weeks. Do you think you will have time to look at this feature by then? Thank you very much. :-)

**Comment by mhkeller** [comment]
Yes sorry for the delay. Let me take a look.

**Comment by mhkeller** [comment]
@Globulle take a look at the latest via https://github.com/mhkeller/pulp2/commit/bd08bb191b4712cacfebc304f4eb9700ba0c6bb8 https://github.com/mhkeller/pulp2/commit/2bf5145fa5ac34806431668fd360a858351c4983. I tested on FF, Chrome and Safari on mac. It should fade in if you hover near the top. I didn't do it animating in from the to since Chrome and Safari have their own stuff that comes in from the top and there wasn't a nice way to do it with enough space so you don't accidentally trigger that. 

Let me know if that works and I'll close this one.

**Comment by Globulle** [comment]
[This is perfect](http://pellichi.fr/manga)! Thank you!
